### ISSUE TITLE
Will the code of Flux be open source?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [voteflux/voteflux.github.io#9]
Developing participation platform in a non-participatory way is a bit weird.

**Comment by XertroV** [comment]
Closing issue because this isn't the place for it. 

Current thinking is everything will be GPL2 or similar.

**Comment by KrzysztofMadejski** [comment]
I'd recommend [AGPL v3](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License) then (A stands for Affero, this licence is a cousin of GPL dedicated to webservices, whereas GPL is for compiled libraries, to say it shortly)

**Comment by XertroV** [comment]
Cool, thanks for the suggestion.

Will probably not license it to begin with and then choose an appropriate license. [Seems like this is okay](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license)

AGPL looks good. I think we need a licensing nerd to really help with deciding. Full ramifications aren't super clear to me yet.

Particularly, we want to stop particular entities (like nation-states) using it for free, but let the open source community go wild.
